version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ../certs:/mosquitto/certs
    ports:
      - "8883:8883"
